server:
  port: 8081
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.Route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path= /accounts/v1/**